/*
 *    DTV tuner linux driver
 *
 * Usage:    DTV tuner driver by i2c for linux
 *
 *
 * This software program is licensed subject to the GNU General Public License
 * (GPL).Version 2,June 1991, available at http://www.fsf.org/copyleft/gpl.html
 *
 */

#include "dtvd_tuner_com.h"
#include "dtvd_tuner_state.h"

static const DTVD_TUNER_STATE_ACT_REQUEST_t* dtvd_tuner_state_com_get_action
(
    unsigned char,
    unsigned int,
    unsigned int
);

void dtvd_tuner_state_com_set_status
(
    signed int next_state                               
)
{

    tdtvd_tuner_state.status = next_state;

    return;
}

signed int dtvd_tuner_state_com_read( void )
{
    signed int                  ret;
    unsigned char               addr;
    unsigned char               data;

    addr = D_DTVD_TUNER_REG_SYNC_STATE;
    data = 0x00;

    ret = dtvd_tuner_com_dev_i2c_read( D_DTVD_TUNER_REG_NO1, &addr, &data );
    if( ret != D_DTVD_TUNER_OK )
    {
        return D_DTVD_TUNER_NG;
    }

    tdtvd_tuner_state.state_new = (unsigned int)data;

    return D_DTVD_TUNER_OK;

}

void dtvd_tuner_state_com_watch_timer_start( void )
{

    dtvd_tuner_timer_start( D_DTVD_TUNER_TIMER_WATCH_STATE,
                            tdtvd_tuner_state.cycle_time );

    return;
}

void dtvd_tuner_state_com_watch_timer_stop( void )
{

    dtvd_tuner_timer_stop( D_DTVD_TUNER_TIMER_WATCH_STATE );

    return;
}

void dtvd_tuner_state_com_state_init( void )
{

    tdtvd_tuner_state.state_old = D_DTVD_TUNER_STATE_S0;

    tdtvd_tuner_state.state_new = D_DTVD_TUNER_STATE_S0;

    return;
}

void dtvd_tuner_state_com_action
(
    unsigned char   kind            
)
{
    const DTVD_TUNER_STATE_ACT_REQUEST_t* actp;

    if( kind >= D_DTVD_TUNER_STATE_TBL_MAX )
    {

        DTVD_TUNER_SYSERR_RANK_A( D_DTVD_TUNER_SYSERR_DRV_PARAM,
                                  DTVD_TUNER_STATE_COM,
                                  (unsigned long)kind, 0, 0, 0, 0, 0 );
        return;
    }

    actp = dtvd_tuner_state_com_get_action( kind,
                                            tdtvd_tuner_state.state_old,
                                            tdtvd_tuner_state.state_new );
    if( actp == D_DTVD_TUNER_NULL )
    {

        DTVD_TUNER_SYSERR_RANK_A( D_DTVD_TUNER_SYSERR_DRV_PARAM,
                                  DTVD_TUNER_STATE_COM,
                                  0, 0, 0, 0, 0, 0 );
        return;
    }

    if( (actp->event & D_DTVD_TUNER_STATE_ACT_ERR) != 0 )
    {

        DTVD_TUNER_SYSERR_RANK_A( D_DTVD_TUNER_SYSERR_DRV_STATE,
                                  DTVD_TUNER_STATE_COM,
                                  tdtvd_tuner_state.state_old,
                                  tdtvd_tuner_state.state_new, 0, 0, 0, 0 );
        return;
    }

    if( (actp->event & D_DTVD_TUNER_STATE_ACT_MODE) != 0 )
    {

        dtvd_tuner_state_trans_msg_mode_ok();
    }

    if( (actp->event & D_DTVD_TUNER_STATE_ACT_SYNC) != 0 )
    {

        dtvd_tuner_state_trans_msg_sync();
    }

    if( (actp->event & D_DTVD_TUNER_STATE_ACT_TMCC) != 0 )
    {

        dtvd_tuner_state_trans_msg_tmcc();
    }

    if( (actp->event & D_DTVD_TUNER_STATE_ACT_TSOUT) != 0 )
    {

        dtvd_tuner_state_trans_msg_tsout();
    }

    if( (actp->event & D_DTVD_TUNER_STATE_ACT_ASYNC) != 0 )
    {

        dtvd_tuner_state_trans_msg_async();
    }

    tdtvd_tuner_state.state_old = actp->next_state;

    return;
}

static const DTVD_TUNER_STATE_ACT_REQUEST_t* dtvd_tuner_state_com_get_action
(
    unsigned char   kind,           
    unsigned int    old_state,      
    unsigned int    new_state       
)
{

    static const DTVD_TUNER_STATE_ACT_REQUEST_MTX_t tbl_watch =
    {

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S1, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S2, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S3, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S4, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S1, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S2, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S3, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S4, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S1, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S2, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S3, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S4, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S3, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S4, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S4, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_NONE } 
        }
    };

    static const DTVD_TUNER_STATE_ACT_REQUEST_MTX_t tbl_sync =
    {

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S1, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S2, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S3, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S4, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S1, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S2, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S3, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S4, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S1, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S2, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S3, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S4, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S3, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S4, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S4, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_NONE  },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_NONE  } 
        }

    };

    static const DTVD_TUNER_STATE_ACT_REQUEST_MTX_t tbl_tsout =
    {

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S1, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S2, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S3, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S4, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S1, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S2, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S3, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S4, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S1, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S2, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S3, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S4, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_MODE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_MODE | D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S3, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S4, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S4, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S5, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S6, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_SYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_SYNC | D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S7, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_TMCC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_TMCC | D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S8, D_DTVD_TUNER_STATE_ACT_NONE },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_TSOUT } 
        },

        { 
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S0, D_DTVD_TUNER_STATE_ACT_ASYNC },
        { D_DTVD_TUNER_STATE_S9, D_DTVD_TUNER_STATE_ACT_TSOUT } 
        }
    };

    static const DTVD_TUNER_STATE_ACT_REQUEST_MTX_t * const tbl[] =
    {
        &tbl_watch,         
        &tbl_sync,          
        &tbl_tsout          
    };

    const DTVD_TUNER_STATE_ACT_REQUEST_MTX_t * actp;

    if( kind >= D_DTVD_TUNER_STATE_TBL_MAX )
    {

        DTVD_TUNER_SYSERR_RANK_A( D_DTVD_TUNER_SYSERR_DRV_PARAM,
                                  DTVD_TUNER_STATE_COM,
                                  0, 0, 0, 0, 0, 0 );
        return D_DTVD_TUNER_NULL;
    }

    if( (old_state >= D_DTVD_TUNER_STATE_S_MAX) || (new_state >= D_DTVD_TUNER_STATE_S_MAX) )
    {

        DTVD_TUNER_SYSERR_RANK_A( D_DTVD_TUNER_SYSERR_DRV_PARAM,
                                  DTVD_TUNER_STATE_COM,
                                  0, 0, 0, 0, 0, 0 );
        return D_DTVD_TUNER_NULL;
    }

    actp = tbl[kind];
    return &(*actp)[old_state][new_state];

}

